---
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, '3.10', 3.12]
        architecture: ['x64']
        include:
          - os: ubuntu-20.04
            python-version: 3.6
            architecture: 'x64'
          - os: macos-latest
            python-version: 3.12
            architecture: 'x64'
          - os: windows-latest
            python-version: 3.12
            architecture: 'x64'

      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install
        run: |
          pip install wheel toml setuptools
          pip install -e .[test]

      - name: Build
        run: python setup.py build
        env:
          CC_FLAGS: -D COUNT_COLLISIONS

      - name: Test
        run: pytest
        env:
          FORCE_COLOR: 1

      # Test PyInstaller.
      - run: pip uninstall -y hirola && pip install .
      - run: pip install pyinstaller
      - working-directory: tests/PyInstaller_
        run: pyinstaller frozen-pytest.spec
      - working-directory: tests/PyInstaller_
        run: ./dist/frozen-pytest/frozen-pytest ../..
